name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

env:
  SERVICE_NAME: ms-post

jobs:
  ci:
    uses: Volontariapp/ci-tools/.github/workflows/ci-service.yml@main
    with:
      service-name: ${{ github.env.SERVICE_NAME }}
    secrets: inherit
  
  ci-docker:
    needs: ci
    uses: Volontariapp/ci-tools/.github/workflows/docker-build-push.yml@main
    with:
      service_name: ${{ github.env.SERVICE_NAME }}
    secrets: inherit
